### ISSUE TITLE
Low AI feature request

### ISSUE THREAD

**Issue by havocfire** [Xanfre/T2Fix#1]
Hi, could you create new AI detection level where AI is not so observable? So sneaking up would be much easier despite the sound produced.

**Comment by Xanfre** [comment]
This project is really just intended to provide an easy way to patch a Thief 2 installation with NewDark while also optionally providing the ability to install a few popular mods if you choose the setup executable that includes them. It does not provide any new features to the game beyond what NewDark itself does. Also, as of now, there are no plans to include any additional mods, though this does still remain a possibility. Further, one criterion of the included mods is that they do not significantly change the way the game is played. For example, mods that patch flaws in the original game are ideal for inclusion. On the other hand, something that modifies how AI detection behaves is probably not appropriate to be in T2Fix itself.

All of this said, implementing something like you describe is entirely possible from a technical standpoint. However, doing this would be most appropriate for a standalone mod rather than T2Fix. Unfortunately, I am aware of no such mod that currently includes this functionality.
